development:
  adapter: mysql2
  database: 10cp
  host: localhost
  username: root
  password: p@ssw0rd

test:
  adapter: mysql2
  database: 10cp_test
  host: localhost
  username: root
  password: p@ssw0rd
